service: hub-api
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  environment:
    COGNITO_USER_POOL_ID: eu-central-1_2aEk8Onki
    COGNITO_APP_CLIENT_ID: heajnhd40jrihjlv70k3m6o8u
    JWT_SECRET: ${env:JWT_SECRET}
    PRODUCTS_TABLE: ${env:PRODUCTS_TABLE}
    STRIPE_SECRET_KEY: ${env:STRIPE_SECRET_KEY}
    FRONTEND_URLS: ${env:FRONTEND_URLS}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
        - dynamodb:Query
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:eu-central-1:941377144465:table/hub_sessions
        - arn:aws:dynamodb:eu-central-1:941377144465:table/hub_codes
        - arn:aws:dynamodb:eu-central-1:941377144465:table/hub_users
        - arn:aws:dynamodb:eu-central-1:941377144465:table/Products

  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
        - https://dev.d3idv4br2ibj8m.amplifyapp.com
        - https://dev.d1xuz6wpo1v9ag.amplifyapp.com
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowCredentials: true

plugins:
  - serverless-esbuild

functions:
  createSession:
    handler: src/handlers/auth/session.handler
    events:
      - httpApi:
          path: /auth/session
          method: post

  exchange:
    handler: src/handlers/auth/exchange.handler
    events:
      - httpApi:
          path: /auth/exchange
          method: post

  profile:
    handler: src/handlers/auth/profile.handler
    events:
      - httpApi:
          path: /auth/profile
          method: get

  me:
    handler: src/handlers/auth/me.handler
    events:
      - httpApi:
          path: /auth/me
          method: get

  logout:
    handler: src/handlers/auth/logout.handler
    events:
      - httpApi:
          path: /auth/logout
          method: post

  postConfirmation:
    handler: src/handlers/auth/postConfirmation.handler
    events:
      - cognitoUserPool:
          pool: ${env:COGNITO_USER_POOL_ID}
          trigger: PostConfirmation
          existing: true

  addProduct:
    handler: src/handlers/products/add.handler
    events:
      - httpApi:
          path: /products
          method: post

  getProducts:
    handler: src/handlers/products/get.handler
    events:
      - httpApi:
          path: /products
          method: get

  updateProduct:
    handler: src/handlers/products/update.handler
    events:
      - httpApi:
          path: /products
          method: put

  deleteProduct:
    handler: src/handlers/products/delete.handler
    events:
      - httpApi:
          path: /products
          method: delete


  createCheckoutSession:
    handler: src/handlers/payments/createCheckoutSession.handler
    events:
      - httpApi:
          path: /payments/create-checkout-session
          method: post
